- Naive bayes merupakan teori probabiltias dasar yang dapat digunakan sebagai klasifikasi AI

- Dataset "titanic.csv" merepsentasikan penumpang mana saja yang hidup berdasarkan kriteria2 yang tersedia.

- Buatlah system klasifikasi menggunakan naive bayes menggunakan metode Naive Bayes.

- Saya legalkan teman2 menggunakan library sklearn untuk membuat algorima naive bayes

- Pengjelasan code di kirimkan dalam bentuk pdf atau gitlab (bebas) . 
- Jika dalam bentuk gitlab, setup link menjadi public

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Titanic.csv to Titanic.csv


In [3]:
uploaded

{'Titanic.csv': b'Name,PClass,Age,Sex,Survived\r\n"Allen, Miss Elisabeth Walton",1st,29,female,1\r\n"Allison, Miss Helen Loraine",1st,2,female,0\r\n"Allison, Mr Hudson Joshua Creighton",1st,30,male,0\r\n"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25,female,0\r\n"Allison, Master Hudson Trevor",1st,0.92,male,1\r\n"Anderson, Mr Harry",1st,47,male,1\r\n"Andrews, Miss Kornelia Theodosia",1st,63,female,1\r\n"Andrews, Mr Thomas, jr",1st,39,male,0\r\n"Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58,female,1\r\n"Artagaveytia, Mr Ramon",1st,71,male,0\r\n"Astor, Colonel John Jacob",1st,47,male,0\r\n"Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,19,female,1\r\n"Aubert, Mrs Leontine Pauline",1st,,female,1\r\n"Barkworth, Mr Algernon H",1st,,male,1\r\n"Baumann, Mr John D",1st,,male,0\r\n"Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,50,female,1\r\n"Baxter, Mr Quigg Edmond",1st,24,male,0\r\n"Beattie, Mr Thomson",1st,36,male,0\r\n"Beckwith, Mr Richard Leord",1st,37,male,1\r\n

In [9]:
# Importing dataset
data = pd.read_csv("Titanic.csv")

# Convert categorical variable to numeric
data["Sex_cleaned"]=np.where(data["Sex"]=="male",0,1)

In [10]:
data

Name PClass    Age     Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00  female   
1                       Allison, Miss Helen Loraine    1st   2.00  female   
2               Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                     Allison, Master Hudson Trevor    1st   0.92    male   
...                                             ...    ...    ...     ...   
1308                             Zakarian, Mr Artun    3rd  27.00    male   
1309                         Zakarian, Mr Maprieder    3rd  26.00    male   
1310                               Zenni, Mr Philip    3rd  22.00    male   
1311                               Lievens, Mr Rene    3rd  24.00    male   
1312                                 Zimmerman, Leo    3rd  29.00    male   

      Survived  Sex_cleaned  
0            1            1  
1            0            1  
2            0            0  
3            0            1  
4            1            0  
...        ...          ...  
1308         0            0  
1309         0            0  
1310         0            0  
1311         0            0  
1312         0            0  

[1313 rows x 6 columns]

In [11]:

# Cleaning dataset of NaN
data=data[[
    "Survived",
    "Sex_cleaned",
    "Age"
]].dropna(axis=0, how='any')

In [19]:
data

Survived  Sex_cleaned    Age
0            1            1  29.00
1            0            1   2.00
2            0            0  30.00
3            0            1  25.00
4            1            0   0.92
...        ...          ...    ...
1308         0            0  27.00
1309         0            0  26.00
1310         0            0  22.00
1311         0            0  24.00
1312         0            0  29.00

[756 rows x 3 columns]

In [12]:
used_features =[
    "Sex_cleaned",
    "Age"
]

In [17]:
used_features

['Sex_cleaned', 'Age']

In [14]:
X = data[used_features].values
y = data["Survived"]

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [28]:
X_train

array([[ 0.,  4.],
       [ 1., 54.],
       [ 0., 22.],
       ...,
       [ 0., 24.],
       [ 0., 30.],
       [ 0., 48.]])

In [27]:
y_train

895     1
216     1
1279    1
890     0
98      0
       ..
93      1
134     0
373     1
598     0
129     1
Name: Survived, Length: 506, dtype: int64

In [47]:
gnb = GaussianNB()
gnb_fit = gnb.fit(X_train, y_train)
y_pred = gnb_fit.predict(X)

In [49]:
X

array([[ 1., 29.],
       [ 1.,  2.],
       [ 0., 30.],
       ...,
       [ 0., 22.],
       [ 0., 24.],
       [ 0., 29.]])

In [48]:
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,

In [40]:
y_pred_proba = gnb_fit.predict_proba(X_test)

In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.86      0.82       144
           1       0.78      0.69      0.73       106

    accuracy                           0.79       250
   macro avg       0.79      0.77      0.78       250
weighted avg       0.79      0.79      0.79       250

